[features]
seeds = false
[programs.localnet]
serum_market_deploy = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
serum_market_deploy = "G5v3swMsJbi2pM6QgGu7rSMKHFd2f5ybn8WuGpMqTdBJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/mertwole/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
